services:
  java:
    build: .
    container_name: skill-bridge
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGPASSWORD: felipe
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: skillbridge
      GROQ_API_KEY: ${GROQ_API_KEY}
    networks:
      - private-network

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: felipe
      POSTGRES_DB: skillbridge
    ports:
      - "5431:5432"
    networks:
      - private-network

networks:
  private-network:
    driver: bridge
